export const GROUP_SUBMISSION_MAX_FILE_SIZE_MB = 5;
export const GROUP_SUBMISSION_MAX_FILE_SIZE_BYTES = GROUP_SUBMISSION_MAX_FILE_SIZE_MB * 1024 * 1024;

export const SERVER_ACTION_BODY_SIZE_LIMIT = '6mb';
