export type UiLanguage = 'en' | 'fr';

export const UI_LANGUAGE_COOKIE_NAME = 'teaching-aid-ui-language';
export const UI_LANGUAGE_STORAGE_KEY = 'teaching-aid-ui-language';
export const UI_LANGUAGE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;

export function normalizeUiLanguage(value: string | null | undefined): UiLanguage {
  return value === 'fr' ? 'fr' : 'en';
}

export function getUiLanguageFromCookieValue(value: string | undefined | null): UiLanguage {
  return normalizeUiLanguage(typeof value === 'string' ? value : undefined);
}

export function formatUiDateTime(value: string | Date, language: UiLanguage) {
  const date = typeof value === 'string' ? new Date(value) : value;
  const locale = language === 'fr' ? 'fr-FR' : 'en-GB';

  return date.toLocaleString(locale, {
    dateStyle: 'medium',
    timeStyle: 'short'
  });
}

const UI_TEXT = {
  en: {
    shared: {
      teacherAdmin: 'Teacher admin',
      sessions: 'Sessions',
      backToSessionsHub: 'back to sessions hub',
      programme: 'Programme',
      date: 'Date',
      notSet: 'Not set',
      close: 'Close',
      cancel: 'Cancel',
      deleteSession: 'Delete session',
      deleteSessionConfirmTitle: 'Delete session?',
      deleteSessionConfirmBody:
        'This action is intentional and cannot be undone. Deleting "{title}" will remove the session and all dependent data.',
      deleteSessionConfirmAction: 'Delete session',
      deletingSession: 'Deleting...'
    },
    sessionsHub: {
      title: 'Sessions',
      subtitle: 'Teacher admin',
      description: 'Create and manage peer-to-peer sessions.',
      newSession: 'New session',
      columns: {
        title: 'Title',
        language: 'Language',
        groupLock: 'Group lock',
        orderLock: 'Order lock',
        studentWork: 'Student work',
        created: 'Created',
        actions: 'Actions'
      },
      empty: 'No sessions yet. Create the first one to get started.',
      locked: 'Locked',
      open: 'Open',
      resume: 'Resume',
      public: 'Public',
      setup: 'Setup',
      groups: 'Groups',
      uploadStudentsWork: 'Upload students work',
      createGroupsFirst: 'Create groups first.',
      noWorkUploaded: 'No work uploaded yet.',
      deletesOn: 'Deletes on {date}'
    },
    globalSettings: {
      label: 'Global settings',
      passwordPrompt: 'Enter the global settings password',
      wrongPassword: 'Incorrect password.'
    },
    sessionAdmin: {
      settings: 'Settings',
      sessionContext: 'Session context',
      editSessionContext: 'Edit session context',
      edit: 'Edit',
      undo: 'Undo',
      saveContext: 'Save context',
      changesSavedAcrossSession: 'Changes save immediately across the session.',
      assignmentBrief: 'Assignment brief',
      assignmentBriefPlaceholder: 'Describe the activity, expectations, and anything the AI should consider.',
      noAssignmentBrief: 'No assignment brief yet.',
      saveBrief: 'Save brief',
      editAssignmentBrief: 'Edit assignment brief',
      close: 'Close',
      class: 'Class',
      subject: 'Subject',
      intake: 'Intake',
      professor: 'Professor',
      presentationDate: 'Presentation date',
      pairagogieSetup: 'Pairagogie & students setup',
      openStudentsSetup: 'Open students setup',
      sessionContextSummary: 'Session context',
      assignmentBriefSummary: 'Assignment brief'
    },
    sessionStudents: {
      pageSubtitle: 'Manage Pairagogie session metadata and import students from Boostcamp.',
      pageTitle: 'Pairagogie & students setup',
      pairagogieStudentsSetup: 'Pairagogie & students setup',
      importStudents: 'Import students',
      importHelp:
        'Upload a Boostcamp `.xlsx` file, paste Boostcamp roster text, or use a CSV with first name, last name, school email, and optional user ID columns.',
      fileUpload: 'File upload',
      dragFileHere: 'Drag and drop a `.xlsx` or `.csv` file here, or choose one manually.',
      pasteRosterText: 'Paste Boostcamp roster text',
      parsePastedText: 'Parse pasted text',
      row: 'Row',
      userId: 'User ID',
      status: 'Status',
      importing: 'Importing...',
      importValidRows: 'Import valid rows',
      boostcampGuideTitle: 'Boostcamp import instructions',
      boostcampCsvGuideTitle: 'CSV',
      boostcampCsvGuideSteps: [
        'Log in to Boostcamp.',
        'Enter your course.',
        'Enter the episode where you want to create the groups.',
        'Click the gear icon at the top of the screen. A menu will open.',
        'Click Participants.',
        'At the bottom of the page, click “Select all XX users”.',
        'In the dropdown next to the Select button (“With selected users… Choose…”), click “Comma Separated values (.csv)”.',
        'Upload the file here.'
      ],
      boostcampTextGuideTitle: 'Text',
      boostcampTextGuideSteps: [
        'Log in to Boostcamp.',
        'Enter your course.',
        'Enter the episode where you want to create the groups.',
        'Click the gear icon at the top of the screen. A menu will open.',
        'Click Groups (last column of the menu, “User links”).',
        'Select the class that interests you.',
        'Select all users by clicking from outside of the list box and selecting all users within the box.',
        'Copy (Ctrl+C or Command+C).',
        'Paste here (Ctrl+V or Command+V).'
      ],
      groupsLink: 'Groups',
      evaluationLink: 'Evaluation',
      sessionsListLink: 'Sessions list',
      metadataTitle: 'Pairagogie session metadata',
      metadataDescription: 'Save the session details used by exports.',
      suggestedFromImport: 'Suggested from imported Boostcamp data.',
      studentsImportButton: 'Students update/import',
      updateStudents: 'Update students',
      startStudentsImport: 'Start students import',
      chooseWithGroups: 'Choose whether the incoming file includes groups or only roster data.',
      chooseFirstImport: 'Choose how to begin the first import for this session.',
      updateWithGroups: 'Update with groups',
      updateWithoutGroups: 'Update without groups',
      startFromScratch: 'No. Start from scratch',
      uploadCsv: "Yes. I'll upload the CSV file",
      pasteRoster: 'Paste Boostcamp roster text',
      updateFromCsv: 'Update from CSV file',
      back: 'Back',
      className: 'Class name',
      classLanguage: 'Class language',
      french: 'French',
      english: 'English',
      saveSetup: 'Save Pairagogie & students setup',
      importedStudents: 'Imported students',
      rosterDescription: 'Students already saved in this session roster.',
      noStudents: 'No students imported yet.',
      firstName: 'First name',
      lastName: 'Last name',
      schoolEmail: 'School email',
      importedAt: 'Imported at',
      setupModalTitle: 'Pairagogie & students setup'
    },
    sessionGroups: {
      subtitle: 'Group creation',
      description: 'Create, rename, resize, and manage session groups.',
      groupsTitle: 'Groups',
      publicPage: 'Enrolment Page',
      resume: 'Resume',
      sessionsList: 'Sessions list',
      testGroups: 'Test groups',
      createDefaultGroups: 'Create default groups',
      noGroupsYet: 'No groups exist yet.',
      createGroupsHelp: 'Create {count} groups using the session default capacity to start assigning students.',
      createDefaultGroupsButton: 'Create default groups',
      unassignedStudents: 'Unassigned students',
      dragToRemove: 'Drag a student card here to remove them from a group.',
      showIgnoredStudents: 'Show ignored students',
      allStudentsAssigned: 'All students are assigned to groups.',
      moveStudentTo: 'Move student to...',
      ignore: 'Ignore',
      createGroupsFirstToAssign: 'Create groups first to assign.',
      ignoredUsers: 'Ignored users',
      restoredUsersReturn: 'Restored users return to the unassigned list.',
      noIgnoredUsers: 'No ignored users.',
      updateAndSave: 'Update and save',
      saveGroup: 'Save group',
      deleteGroup: 'Delete group',
      remove: 'Remove',
      members: 'Members',
      noStudentsInGroup: 'No students in this group yet.',
      createDefaultGroupsToBeginManagingMemberships: 'Create default groups to begin managing memberships.',
      haveUnsavedChanges: 'have unsaved changes.',
      unsavedChanges: 'Unsaved changes',
      savedAndUnchanged: 'Saved and unchanged',
      cap: 'Cap',
      decreaseCapacity: 'Decrease capacity for {name}',
      increaseCapacity: 'Increase capacity for {name}',
      groupDetails: 'Group details',
      presentationOrderNotLocked: 'Presentation order not locked yet.',
      noSubmissionUploaded: 'No submission uploaded yet.',
      groupDetailsTitle: 'Group details',
      scoringAndFeedback: 'Scoring and feedback',
      poweredBy: 'with the power of ExpertLab AI',
      writePresentationNotes: 'Write the live presentation notes here.',
      generateQuestions: 'Generate questions',
      generatingQuestions: 'Generating...',
      pleaseUploadWork: "Please upload the group's work to enable question recommendation.",
      challengeQuestions: 'Challenge questions',
      generating: 'Generating',
      sendToAi: 'Send the notes or uploaded work to AI for structured feedback and conservative grade suggestions.',
      addCommentsFirst: 'Add comments or upload work before generating AI feedback and grades.',
      generateFeedback: 'Generate AI feedback & grades',
      generatingFeedback: 'Generating feedback...',
      finalGrading: 'Final grading',
      finalGradingTitle: 'Final grading',
      aiStatus: 'AI status',
      criterion: 'Criterion',
      finalScore: 'Final score',
      max: 'Max',
      finalTotal: 'Final total',
      totalCalculatedFromTeacherScores: 'The total is calculated from the teacher-controlled scores above.',
      finalFeedback: 'Final feedback',
      editableSummary: 'Editable summary',
      spellCheckFeedback: 'Spell-check feedback',
      strengths: 'Strengths',
      development: 'Points for development',
      general: 'General feedback',
      noGroupsAvailable: 'No groups available'
    },
    sessionOrder: {
      subtitle: 'Presentation order & upload',
      description: 'Generate presentation order and attach one file per group.',
      groups: 'Groups',
      sessionsList: 'Sessions list',
      presentationOrderControls: 'Presentation order controls',
      useButtonsToMove: 'Use the buttons to move groups or randomize the order.',
      generateOrder: 'Generate a random order or move groups manually to set the sequence.',
      noGroupsYet: 'No groups yet',
      createGroupsFirst: 'Create groups first, then come back here to assign presentation order and upload files.',
      goToGroups: 'Go to groups',
      order: 'Order',
      notLocked: 'Not locked in yet',
      capacity: 'Capacity',
      uploadedFile: 'Uploaded file',
      noFileUploaded: 'No file uploaded yet.',
      moveUp: 'Move up',
      moveDown: 'Move down',
      uploadFile: 'Upload file'
    },
    sessionEvaluation: {
      subtitle: 'AI scoring & feedback',
      description: 'Evaluate groups in presentation order, save live notes, and use batch or per-group AI support.',
      exports: 'Exports'
    },
    evaluationWorkspace: {
      aiStatusFailed: 'Failed',
      aiStatusGenerating: 'Generating',
      aiStatusIdle: 'Idle',
      aiStatusReady: 'Ready',
      generateAllQuestions: 'Generate all questions',
      generatingAllQuestions: 'Generating all questions...',
      generateAllFeedback: 'Generate all groups feedback',
      generatingAllFeedback: 'Generating all groups feedback...',
      activityInstructions: 'Activity instructions',
      briefUsedByAi: 'This brief is used by the AI question and feedback workflow.',
      showPublicQr: 'Show QR code',
      scanToEnrolInGroup: 'Scan to enrol to a group',
      assignmentBrief: 'Assignment brief',
      saveBrief: 'Save brief',
      describeActivity: 'Describe the activity, expectations, and anything the AI should consider.',
      noGroupsAvailable: 'No groups available',
      roster: 'Roster',
      groupDetails: 'Group details',
      presentationOrderNotLocked: 'Presentation order not locked yet.',
      noSubmissionUploaded: 'No submission uploaded yet.',
      scoringAndFeedback: 'Scoring and feedback',
      poweredBy: 'with the power of ExpertLab AI',
      writePresentationNotes: 'Write the live presentation notes here.',
      renameGroup: 'Rename group',
      renameGroupLabel: 'Rename {name}',
      generateQuestions: 'Generate questions',
      regenerateQuestions: 'Regenerate questions',
      generatingQuestions: 'Generating...',
      pleaseUploadWork: "Please upload the group's work to enable question recommendation.",
      couldNotGenerateChallengeQuestions: 'Could not generate challenge questions.',
      generateQuestionsFromWork: 'Generate questions from the uploaded work to prepare the oral defense.',
      challengeQuestions: 'Challenge questions',
      sendingNotes: 'Send the notes or uploaded work to AI for structured feedback and conservative grade suggestions.',
      addCommentsFirst: 'Add comments or upload work before generating AI feedback and grades.',
      generateFeedback: 'Generate AI feedback & grades',
      generatingFeedback: 'Generating feedback...',
      finalGrading: 'Final grading',
      aiStatus: 'AI status',
      criterion: 'Criterion',
      finalScore: 'Final score',
      max: 'Max',
      finalTotal: 'Final total',
      finalFeedback: 'Final feedback',
      editableSummary: 'Editable summary',
      spellCheckFeedback: 'Spell-check feedback',
      strengths: 'Strengths',
      development: 'Points for development',
      general: 'General feedback',
      finalGrade: 'Final grade',
      noGrade: 'No grade',
      noGradeYet: 'No grade yet',
      selectedStudent: 'Selected student',
      students: 'Students',
      moveToGroup: 'Move to group',
      chooseDestination: 'Choose a destination',
      moveStudent: 'Move student',
      removeFromAllGroups: 'Remove from all groups',
      individualGrading: 'Individual grading',
      adjustment: 'Adjustment',
      signedAdjustmentPlaceholder: '+1 or -1',
      signedAdjustmentHelp: 'Apply a signed whole-number adjustment. The student&apos;s final grade stays between 0 and 20.',
      selectStudentHint: 'Select a student to move them, remove them, or apply individual grading.',
      noStudentsInGroup: 'No students in this group.',
      close: 'Close',
      saving: 'Saving...',
      saved: 'Saved.',
      enterSignedAdjustment: 'Enter a signed whole-number adjustment.',
      chooseDestinationGroup: 'Choose a destination group.',
      couldNotSaveRosterChange: 'Could not save roster change.',
      rosterTitle: 'Group roster',
      gradeLabel: 'Grade {grade}',
      adjustmentLabel: 'Adjustment: {adjustment}',
      finalGradeLabel: 'Final grade: {grade}',
      remainingSeats: '{count} left',
      rosterCount: '{count}',
      finalized: 'Finalized:',
      generated: 'Generated',
      noGroupsHelp: 'Create or assign groups before using the evaluation workspace.',
      resetScores: 'Reset scores',
      markReadyForExport: 'Mark ready for export',
      presentationOrder: 'Presentation order {order}.',
      submission: 'Submission: {title}.',
      thisGroup: 'this group',
      no: 'No',
      qaComments: 'Q&A comments',
      qaCommentsPlaceholder: 'Optional notes for the questions and answers phase.',
      resetCriterionScoresConfirm:
        'Reset all criterion scores for this group? Teacher notes, Q&A notes, AI challenge questions, and final feedback will be kept.',
      batchQuestionsDoneWithSkipped:
        'Generated questions for eligible groups. {count} group(s) skipped.',
      batchQuestionsDoneAll: 'Generated questions for all eligible groups.',
      batchFeedbackDoneWithSkipped:
        'Generated feedback and grades for eligible groups. {count} group(s) skipped.',
      batchFeedbackDoneAll: 'Generated feedback and grades for all eligible groups.',
      errors: {
        renameGroup: 'Could not rename the group.',
        updatePresentationOrder: 'Could not update presentation order.',
        saveChanges: 'Could not save changes.',
        regenerateChallengeQuestions: 'Could not regenerate challenge questions.',
        generateAiRecommendations: 'Could not generate AI recommendations.',
        runBatchAi: 'Could not run batch AI.',
        runSpellCheck: 'Could not run spell-check.',
        finalizeGroup: 'Could not finalize this group.'
      }
    },
    rosterDialog: {
      title: 'Group roster',
      students: 'Students',
      selectedStudent: 'Selected student',
      noGrade: 'No grade',
      noGradeYet: 'No grade yet',
      moveToGroup: 'Move to group',
      chooseDestination: 'Choose a destination',
      moveStudent: 'Move student',
      removeFromAllGroups: 'Remove from all groups',
      individualGrading: 'Individual grading',
      adjustment: 'Adjustment',
      signedAdjustmentPlaceholder: '+1 or -1',
      signedAdjustmentHelp: 'Apply a signed whole-number adjustment. The student’s final grade stays between 0 and 20.',
      selectStudentHint: 'Select a student to move them, remove them, or apply individual grading.',
      close: 'Close',
      saving: 'Saving...',
      saved: 'Saved.',
      enterSignedAdjustment: 'Enter a signed whole-number adjustment.',
      chooseDestinationGroup: 'Choose a destination group.',
      couldNotSaveRosterChange: 'Could not save roster change.',
      roster: 'Group roster',
      grade: 'Grade {grade}',
      adjustmentValue: 'Adjustment: {adjustment}',
      finalGrade: 'Final grade: {grade}',
      remainingSeats: '{count} left'
    },
    contextPopover: {
      label: 'Session context',
      metadata: 'Metadata',
      close: 'Close'
    },
    randomizeOrder: {
      button: 'Randomize order',
      randomizingOrder: 'Randomizing order...',
      presentationOrder: 'Presentation order',
      randomizingGroups: 'Randomizing groups',
      close: 'Close',
      shuffling: 'The order is being shuffled and saved. Keep this window open until the animation finishes.',
      working: 'Working...',
      saving: 'Saving the final order...',
      saved: 'Presentation order saved. You can close this window.'
    },
    groupSubmission: {
      uploadGroupWork: 'Upload group work',
      dropOrClick: 'Drop a file here or click to choose one for {groupName}.',
      maxFileSize: 'Max file size {size} MB.',
      fileTooLarge: 'The selected file is too large. Max file size {size} MB.',
      compressFirst: 'If your file is larger, you can compress it first using a free tool like',
      uploadedOn: 'Uploaded on {date}',
      dropOrChoose: 'Drop a file or click to choose',
      oneFilePerGroup: 'One file per group. Drag and drop is supported.',
      selectedFile: 'Selected file',
      uploadButton: 'Upload file'
    },
    contextButtons: {
      sessionContext: 'Session context'
    },
    theme: {
      light: 'Switch to light mode',
      dark: 'Switch to dark mode'
    }
  },
  fr: {
    shared: {
      teacherAdmin: 'Admin enseignant',
      sessions: 'Sessions',
      backToSessionsHub: 'retour au hub des sessions',
      programme: 'Programme',
      date: 'Date',
      notSet: 'Non défini',
      close: 'Fermer',
      cancel: 'Annuler',
      deleteSession: 'Supprimer la session',
      deleteSessionConfirmTitle: 'Supprimer la session ?',
      deleteSessionConfirmBody:
        'Cette action est intentionnelle et ne peut pas être annulée. Supprimer "{title}" retirera la session et toutes les données dépendantes.',
      deleteSessionConfirmAction: 'Supprimer la session',
      deletingSession: 'Suppression...'
    },
    sessionsHub: {
      title: 'Sessions',
      subtitle: 'Admin enseignant',
      description: 'Créer et gérer des sessions entre pairs.',
      newSession: 'Nouvelle session',
      columns: {
        title: 'Titre',
        language: 'Langue',
        groupLock: 'Verrou groupes',
        orderLock: "Verrou d'ordre",
        studentWork: 'Travail étudiant',
        created: 'Créée',
        actions: 'Actions'
      },
      empty: 'Aucune session pour le moment. Créez la première pour commencer.',
      locked: 'Verrouillé',
      open: 'Ouvert',
      resume: 'Reprendre',
      public: 'Public',
      setup: 'Setup',
      groups: 'Groupes',
      uploadStudentsWork: 'Téléverser le travail des étudiants',
      createGroupsFirst: 'Créez d’abord les groupes.',
      noWorkUploaded: 'Aucun travail téléversé pour le moment.',
      deletesOn: 'Supprimé le {date}'
    },
    globalSettings: {
      label: 'Paramètres globaux',
      passwordPrompt: 'Saisissez le mot de passe des paramètres globaux',
      wrongPassword: 'Mot de passe incorrect.'
    },
    sessionAdmin: {
      settings: 'Paramètres',
      sessionContext: 'Contexte de session',
      editSessionContext: 'Modifier le contexte de session',
      edit: 'Modifier',
      undo: 'Annuler',
      saveContext: 'Enregistrer',
      changesSavedAcrossSession: 'Les changements sont enregistrés immédiatement pour toute la session.',
      assignmentBrief: 'Consigne',
      assignmentBriefPlaceholder: 'Décrivez l’activité, les attentes et tout ce que l’IA doit prendre en compte.',
      noAssignmentBrief: 'Aucune consigne pour le moment.',
      saveBrief: 'Enregistrer la consigne',
      editAssignmentBrief: 'Modifier la consigne',
      close: 'Fermer',
      class: 'Classe',
      subject: 'Sujet',
      intake: 'Promotion',
      professor: 'Professeur',
      presentationDate: 'Date de présentation',
      pairagogieSetup: 'Pairagogie & étudiants',
      openStudentsSetup: 'Ouvrir les étudiants',
      sessionContextSummary: 'Contexte de session',
      assignmentBriefSummary: 'Consigne'
    },
    sessionStudents: {
      pageSubtitle: 'Gérer les métadonnées Pairagogie et importer les étudiants depuis Boostcamp.',
      pageTitle: 'Pairagogie & étudiants',
      pairagogieStudentsSetup: 'Pairagogie & étudiants',
      importStudents: 'Importer des étudiants',
      importHelp:
        'Téléversez un fichier Boostcamp `.xlsx`, collez le texte de la liste Boostcamp, ou utilisez un CSV avec prénom, nom, email scolaire et éventuellement l’ID utilisateur.',
      fileUpload: 'Téléversement de fichier',
      dragFileHere: 'Glissez et déposez un fichier `.xlsx` ou `.csv` ici, ou choisissez-en un manuellement.',
      pasteRosterText: 'Coller le texte de la liste Boostcamp',
      parsePastedText: 'Analyser le texte collé',
      row: 'Ligne',
      userId: 'ID utilisateur',
      status: 'État',
      importing: 'Importation...',
      importValidRows: 'Importer les lignes valides',
      boostcampGuideTitle: 'Instructions d’import Boostcamp',
      boostcampCsvGuideTitle: 'CSV',
      boostcampCsvGuideSteps: [
        'Connectez-vous à Boostcamp.',
        'Ouvrez votre cours.',
        'Ouvrez l’épisode où vous voulez créer les groupes.',
        'Cliquez sur l’icône d’engrenage en haut de l’écran. Un menu s’ouvrira.',
        'Cliquez sur Participants.',
        'En bas de la page, cliquez sur « Select all XX users ».',
        'Dans la liste déroulante à côté du bouton Select (« With selected users… Choose… »), cliquez sur « Comma Separated values (.csv) ».',
        'Téléversez le fichier ici.'
      ],
      boostcampTextGuideTitle: 'Texte',
      boostcampTextGuideSteps: [
        'Connectez-vous à Boostcamp.',
        'Ouvrez votre cours.',
        'Ouvrez l’épisode où vous voulez créer les groupes.',
        'Cliquez sur l’icône d’engrenage en haut de l’écran. Un menu s’ouvrira.',
        'Cliquez sur Groups (dernière colonne du menu, « User links »).',
        'Sélectionnez la classe qui vous intéresse.',
        'Sélectionnez tous les utilisateurs en cliquant à l’extérieur de la zone de liste, puis en sélectionnant tous les utilisateurs dans la zone.',
        'Copiez (Ctrl+C ou Command+C).',
        'Collez ici (Ctrl+V ou Command+V).'
      ],
      groupsLink: 'Groupes',
      evaluationLink: 'Évaluation',
      sessionsListLink: 'Liste des sessions',
      metadataTitle: 'Métadonnées de session Pairagogie',
      metadataDescription: 'Enregistrer les informations de session utilisées par les exports.',
      suggestedFromImport: 'Suggéré à partir des données Boostcamp importées.',
      studentsImportButton: 'Mettre à jour / importer les étudiants',
      updateStudents: 'Mettre à jour les étudiants',
      startStudentsImport: 'Commencer l’import des étudiants',
      chooseWithGroups: 'Choisissez si le fichier entrant contient les groupes ou seulement la liste des étudiants.',
      chooseFirstImport: 'Choisissez comment démarrer le premier import pour cette session.',
      updateWithGroups: 'Mettre à jour avec les groupes',
      updateWithoutGroups: 'Mettre à jour sans les groupes',
      startFromScratch: 'Non. Commencer de zéro',
      uploadCsv: "Oui. Je téléverserai le fichier CSV",
      pasteRoster: 'Coller le texte de la liste Boostcamp',
      updateFromCsv: 'Mettre à jour depuis un fichier CSV',
      back: 'Retour',
      className: 'Nom de classe',
      classLanguage: 'Langue de classe',
      french: 'Français',
      english: 'Anglais',
      saveSetup: 'Enregistrer Pairagogie & étudiants',
      importedStudents: 'Étudiants importés',
      rosterDescription: 'Étudiants déjà enregistrés dans cette session.',
      noStudents: 'Aucun étudiant importé pour le moment.',
      firstName: 'Prénom',
      lastName: 'Nom',
      schoolEmail: 'Email scolaire',
      importedAt: 'Importé le',
      setupModalTitle: 'Pairagogie & étudiants'
    },
    sessionGroups: {
      subtitle: 'Création des groupes',
      description: 'Créer, renommer, redimensionner et gérer les groupes de session.',
      groupsTitle: 'Groupes',
      publicPage: "Page d'inscription",
      resume: 'Reprendre',
      sessionsList: 'Liste des sessions',
      testGroups: 'Groupes de test',
      createDefaultGroups: 'Créer les groupes par défaut',
      noGroupsYet: "Aucun groupe pour le moment.",
      createGroupsHelp: 'Créez {count} groupes avec la capacité par défaut de la session pour commencer l’affectation des étudiants.',
      createDefaultGroupsButton: 'Créer les groupes par défaut',
      unassignedStudents: 'Étudiants non attribués',
      dragToRemove: 'Glissez une carte étudiant ici pour le retirer d’un groupe.',
      showIgnoredStudents: 'Afficher les étudiants ignorés',
      allStudentsAssigned: 'Tous les étudiants sont attribués à des groupes.',
      moveStudentTo: 'Déplacer l’étudiant vers…',
      ignore: 'Ignorer',
      createGroupsFirstToAssign: 'Créez d’abord les groupes pour affecter les étudiants.',
      ignoredUsers: 'Utilisateurs ignorés',
      restoredUsersReturn: 'Les utilisateurs restaurés reviennent dans la liste non attribuée.',
      noIgnoredUsers: 'Aucun utilisateur ignoré.',
      updateAndSave: 'Mettre à jour et enregistrer',
      saveGroup: 'Enregistrer le groupe',
      deleteGroup: 'Supprimer le groupe',
      remove: 'Retirer',
      members: 'Membres',
      noStudentsInGroup: 'Aucun étudiant dans ce groupe pour le moment.',
      createDefaultGroupsToBeginManagingMemberships: 'Créer les groupes par défaut pour commencer à gérer les membres.',
      haveUnsavedChanges: 'ont des modifications non enregistrées.',
      unsavedChanges: 'Modifications non enregistrées',
      savedAndUnchanged: 'Enregistré et inchangé',
      cap: 'Cap',
      decreaseCapacity: 'Réduire la capacité pour {name}',
      increaseCapacity: 'Augmenter la capacité pour {name}',
      groupDetails: 'Détails du groupe',
      presentationOrderNotLocked: "L’ordre de présentation n’est pas encore verrouillé.",
      noSubmissionUploaded: 'Aucun fichier déposé pour le moment.',
      groupDetailsTitle: 'Détails du groupe',
      scoringAndFeedback: 'Notation et retour',
      poweredBy: 'avec la puissance de ExpertLab AI',
      writePresentationNotes: 'Rédigez ici les notes de la présentation en direct.',
      generateQuestions: 'Générer des questions',
      generatingQuestions: 'Génération...',
      pleaseUploadWork: "Veuillez téléverser le travail du groupe pour activer les questions recommandées.",
      challengeQuestions: 'Questions de défi',
      generating: 'Génération',
      sendToAi: 'Envoyer les notes ou le travail téléversé à l’IA pour obtenir des retours structurés et des suggestions de notes prudentes.',
      addCommentsFirst: 'Ajoutez des commentaires ou téléversez le travail avant de générer les retours et notes IA.',
      generateFeedback: 'Générer les retours et notes IA',
      generatingFeedback: 'Génération des retours...',
      finalGrading: 'Notation finale',
      finalGradingTitle: 'Notation finale',
      aiStatus: "État de l’IA",
      criterion: 'Critère',
      finalScore: 'Note finale',
      max: 'Max',
      finalTotal: 'Total final',
      totalCalculatedFromTeacherScores: 'Le total est calculé à partir des notes contrôlées par l’enseignant ci-dessus.',
      finalFeedback: 'Retour final',
      editableSummary: 'Résumé modifiable',
      spellCheckFeedback: 'Vérifier l’orthographe',
      strengths: 'Points forts',
      development: 'Axes de développement',
      general: 'Retour général',
      noGroupsAvailable: 'Aucun groupe disponible'
    },
    sessionOrder: {
      subtitle: 'Ordre de présentation & dépôt',
      description: 'Générer l’ordre de présentation et associer un fichier par groupe.',
      groups: 'Groupes',
      sessionsList: 'Liste des sessions',
      presentationOrderControls: "Contrôles de l’ordre de présentation",
      useButtonsToMove: 'Utilisez les boutons pour déplacer les groupes ou randomiser l’ordre.',
      generateOrder: 'Générez un ordre aléatoire ou déplacez les groupes manuellement pour définir la séquence.',
      noGroupsYet: 'Aucun groupe',
      createGroupsFirst: 'Créez d’abord les groupes, puis revenez ici pour définir l’ordre de présentation et téléverser les fichiers.',
      goToGroups: 'Aller aux groupes',
      order: 'Ordre',
      notLocked: "Pas encore verrouillé",
      capacity: 'Capacité',
      uploadedFile: 'Fichier téléversé',
      noFileUploaded: 'Aucun fichier téléversé pour le moment.',
      moveUp: 'Monter',
      moveDown: 'Descendre',
      uploadFile: 'Téléverser le fichier'
    },
    sessionEvaluation: {
      subtitle: 'Notation et retour IA',
      description: 'Évaluer les groupes dans l’ordre de présentation, enregistrer les notes en direct et utiliser l’aide IA par groupe ou en lot.',
      exports: 'Exports'
    },
    evaluationWorkspace: {
      aiStatusFailed: 'Échec',
      aiStatusGenerating: 'Génération',
      aiStatusIdle: 'En attente',
      aiStatusReady: 'Prêt',
      generateAllQuestions: 'Générer toutes les questions',
      generatingAllQuestions: 'Génération de toutes les questions...',
      generateAllFeedback: 'Générer les retours de tous les groupes',
      generatingAllFeedback: 'Génération des retours de tous les groupes...',
      activityInstructions: 'Consignes de l’activité',
      briefUsedByAi: 'Cette consigne est utilisée par le flux IA de questions et de retours.',
      showPublicQr: 'Afficher le QR code',
      scanToEnrolInGroup: 'Scanner pour rejoindre un groupe',
      assignmentBrief: 'Consigne',
      saveBrief: 'Enregistrer la consigne',
      describeActivity: 'Décrivez l’activité, les attentes et tout ce que l’IA doit prendre en compte.',
      noGroupsAvailable: 'Aucun groupe disponible',
      roster: 'Liste',
      groupDetails: 'Détails du groupe',
      presentationOrderNotLocked: "L’ordre de présentation n’est pas encore verrouillé.",
      noSubmissionUploaded: 'Aucun fichier déposé pour le moment.',
      scoringAndFeedback: 'Notation et retour',
      poweredBy: 'avec la puissance de ExpertLab AI',
      writePresentationNotes: 'Rédigez ici les notes de la présentation en direct.',
      renameGroup: 'Renommer le groupe',
      renameGroupLabel: 'Renommer {name}',
      generateQuestions: 'Générer les questions',
      regenerateQuestions: 'Régénérer les questions',
      generatingQuestions: 'Génération...',
      pleaseUploadWork: "Veuillez téléverser le travail du groupe pour activer les questions recommandées.",
      couldNotGenerateChallengeQuestions: 'Impossible de générer les questions de défi.',
      generateQuestionsFromWork: "Générez des questions à partir du travail téléversé pour préparer la soutenance orale.",
      challengeQuestions: 'Questions de défi',
      sendingNotes: "Envoyer les notes ou le travail téléversé à l’IA pour obtenir des retours structurés et des suggestions de notes prudentes.",
      addCommentsFirst: 'Ajoutez des commentaires ou téléversez le travail avant de générer les retours et notes IA.',
      generateFeedback: 'Générer les retours et notes IA',
      generatingFeedback: 'Génération des retours...',
      finalGrading: 'Notation finale',
      aiStatus: "État de l’IA",
      criterion: 'Critère',
      finalScore: 'Note finale',
      max: 'Max',
      finalTotal: 'Total final',
      finalFeedback: 'Retour final',
      editableSummary: 'Résumé modifiable',
      spellCheckFeedback: 'Vérifier l’orthographe du retour',
      strengths: 'Points forts',
      development: 'Axes de développement',
      general: 'Retour général',
      finalGrade: 'Note finale',
      noGrade: 'Aucune note',
      noGradeYet: 'Aucune note pour le moment',
      selectedStudent: 'Étudiant sélectionné',
      students: 'Étudiants',
      moveToGroup: 'Déplacer vers un groupe',
      chooseDestination: 'Choisir une destination',
      moveStudent: "Déplacer l’étudiant",
      removeFromAllGroups: 'Retirer de tous les groupes',
      individualGrading: 'Notation individuelle',
      adjustment: 'Ajustement',
      signedAdjustmentPlaceholder: '+1 ou -1',
      signedAdjustmentHelp: 'Appliquez un ajustement signé en nombre entier. La note finale de l’étudiant reste entre 0 et 20.',
      selectStudentHint: "Sélectionnez un étudiant pour le déplacer, le retirer ou lui appliquer une notation individuelle.",
      noStudentsInGroup: 'Aucun étudiant dans ce groupe.',
      close: 'Fermer',
      saving: 'Enregistrement...',
      saved: 'Enregistré.',
      enterSignedAdjustment: 'Saisissez un ajustement signé en nombre entier.',
      chooseDestinationGroup: 'Choisissez un groupe de destination.',
      couldNotSaveRosterChange: 'Impossible d’enregistrer la modification du roster.',
      rosterTitle: 'Roster du groupe',
      gradeLabel: 'Note {grade}',
      adjustmentLabel: 'Ajustement : {adjustment}',
      finalGradeLabel: 'Note finale : {grade}',
      remainingSeats: '{count} place(s) restante(s)',
      rosterCount: '{count}',
      finalized: 'Finalisé :',
      generated: 'Généré',
      noGroupsHelp: 'Créez ou attribuez des groupes avant d’utiliser l’espace d’évaluation.',
      resetScores: 'Réinitialiser les notes',
      markReadyForExport: 'Marquer prêt pour export',
      presentationOrder: "Ordre de présentation {order}.",
      submission: 'Dépôt : {title}.',
      thisGroup: 'ce groupe',
      no: 'Non',
      qaComments: 'Commentaires Q&R',
      qaCommentsPlaceholder: 'Notes facultatives pour la phase questions-réponses.',
      resetCriterionScoresConfirm:
        'Réinitialiser toutes les notes de critère pour ce groupe ? Les notes de l’enseignant, les notes Q&R, les questions de défi IA et le retour final seront conservés.',
      batchQuestionsDoneWithSkipped:
        'Questions générées pour les groupes éligibles. {count} groupe(s) ignoré(s).',
      batchQuestionsDoneAll: 'Questions générées pour tous les groupes éligibles.',
      batchFeedbackDoneWithSkipped:
        'Retours et notes générés pour les groupes éligibles. {count} groupe(s) ignoré(s).',
      batchFeedbackDoneAll: 'Retours et notes générés pour tous les groupes éligibles.',
      errors: {
        renameGroup: 'Impossible de renommer le groupe.',
        updatePresentationOrder: "Impossible de mettre à jour l’ordre de présentation.",
        saveChanges: 'Impossible d’enregistrer les modifications.',
        regenerateChallengeQuestions: 'Impossible de régénérer les questions de défi.',
        generateAiRecommendations: 'Impossible de générer les recommandations IA.',
        runBatchAi: 'Impossible d’exécuter l’IA en lot.',
        runSpellCheck: 'Impossible de lancer la vérification orthographique.',
        finalizeGroup: 'Impossible de finaliser ce groupe.'
      }
    },
    rosterDialog: {
      title: 'Roster du groupe',
      students: 'Étudiants',
      selectedStudent: 'Étudiant sélectionné',
      noGrade: 'Aucune note',
      noGradeYet: 'Aucune note pour le moment',
      moveToGroup: 'Déplacer vers un groupe',
      chooseDestination: 'Choisir une destination',
      moveStudent: "Déplacer l’étudiant",
      removeFromAllGroups: 'Retirer de tous les groupes',
      individualGrading: 'Notation individuelle',
      adjustment: 'Ajustement',
      signedAdjustmentPlaceholder: '+1 ou -1',
      signedAdjustmentHelp: 'Appliquez un ajustement signé en nombre entier. La note finale de l’étudiant reste entre 0 et 20.',
      selectStudentHint: "Sélectionnez un étudiant pour le déplacer, le retirer ou lui appliquer une notation individuelle.",
      close: 'Fermer',
      saving: 'Enregistrement...',
      saved: 'Enregistré.',
      enterSignedAdjustment: 'Saisissez un ajustement signé en nombre entier.',
      chooseDestinationGroup: 'Choisissez un groupe de destination.',
      couldNotSaveRosterChange: 'Impossible d’enregistrer la modification du roster.',
      roster: 'Roster du groupe',
      grade: 'Note {grade}',
      adjustmentValue: 'Ajustement : {adjustment}',
      finalGrade: 'Note finale : {grade}',
      remainingSeats: '{count} place(s) restante(s)'
    },
    contextPopover: {
      label: 'Contexte de session',
      metadata: 'Métadonnées',
      close: 'Fermer'
    },
    randomizeOrder: {
      button: "Randomiser l'ordre",
      randomizingOrder: "Randomisation de l'ordre...",
      presentationOrder: 'Ordre de présentation',
      randomizingGroups: 'Randomisation des groupes',
      close: 'Fermer',
      shuffling: "L’ordre est mélangé et enregistré. Gardez cette fenêtre ouverte jusqu’à la fin de l’animation.",
      working: 'En cours...',
      saving: "Enregistrement de l'ordre final...",
      saved: "L'ordre de présentation est enregistré. Vous pouvez fermer cette fenêtre."
    },
    groupSubmission: {
      uploadGroupWork: 'Téléverser le travail du groupe',
      dropOrClick: 'Déposez un fichier ici ou cliquez pour en choisir un pour {groupName}.',
      maxFileSize: 'Taille max {size} Mo.',
      fileTooLarge: 'Le fichier sélectionné est trop volumineux. Taille max {size} Mo.',
      compressFirst: 'Si votre fichier est plus lourd, vous pouvez d’abord le compresser avec un outil gratuit comme',
      uploadedOn: 'Téléversé le {date}',
      dropOrChoose: 'Déposez un fichier ou cliquez pour en choisir un',
      oneFilePerGroup: 'Un fichier par groupe. Le glisser-déposer est pris en charge.',
      selectedFile: 'Fichier sélectionné',
      uploadButton: 'Téléverser le fichier'
    },
    contextButtons: {
      sessionContext: 'Contexte de session'
    },
    theme: {
      light: 'Passer en mode clair',
      dark: 'Passer en mode sombre'
    }
  }
} as const;

export type UiText = (typeof UI_TEXT)['en'];

export function getUiText(language: UiLanguage): UiText {
  return UI_TEXT[language];
}
